version: '3.8'

services:
  db:
    build: .
    image: postgresql-docker-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network

volumes:
  pgdata:

networks:
  postgres_network: